version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: always

  app:
    image: nextcloud
    ports:
      - 60000:80
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      VIRTUAL_HOST: primary.yuzunoha.net
      LETSENCRYPT_HOST: primary.yuzunoha.net
      LETSENCRYPT_EMAIL: studysteadystandby@gmail.com
    restart: always

networks:
  default:
    external:
      name: shared

